service: serverless-store

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  memorySize: 128
  timeout: 30   
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sdb:BatchPutAttributes"
        - "sdb:PutAttributes"
        - "sdb:Select"
      Resource: [
        "arn:aws:sdb:us-east-1:*:domain/Products",
        "arn:aws:sdb:us-east-1:*:domain/ShoppingCart"
      ]
    - Effect: "Allow"
      Action:
        - "dynamodb:Scan"
        - "dynamodb:Query"
        - "dynamodb:PutItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:BatchWriteItem"
      Resource: [
        "arn:aws:dynamodb:us-east-1:*:table/Products",
        "arn:aws:dynamodb:us-east-1:*:table/ShoppingCart"
      ]

functions:
  products:
    handler: functions/products.handler
    events:
      - http: GET products
      - http: POST cart
      - http: OPTIONS cart      
      - http: PUT checkout
      - http: OPTIONS checkout
  