service: hello-serverless

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 512
  timeout: 30
  
functions:
  hello:
    handler: handler.hello
    memorySize: 128
    timeout: 10
    events:
      - http: GET my-service/resource
