service: test-role-statements

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - 's3:PutObject'
        - 's3:GetObject'
      Resource: "arn:aws:s3:::my-bucket-name/*" # use a new bucket name   
      
functions:
  testPermissions:
    handler: handler.testPermissions
       