service: request-data

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  timeout: 30

functions:
  products:
    handler: handler.products
    events:
      - http: GET store/products
  save:
    handler: handler.save
    events:
      - http: POST shopping-cart/save
      - http: OPTIONS shopping-cart/save # the OPTIONs verb is needed when you want to support the POST verb
